# Question 1

In [1]:
import numpy as np

In [8]:
# create an array of 2 rows and 6 columns
# creating element wise comparaison
arrays_a = np.array([[44,55,12,13,44,77],[66,77,12,44,10,41]])

In [7]:
print(arrays_a)

[[44 55 12 13 44 77]
 [66 77 12 44 10 41]]


In [11]:
filter = print(arrays_a > 20)
filter


[[ True  True False False  True  True]
 [ True  True False  True False  True]]


In [12]:
filter = print(arrays_a >= 44)
print(filter)

[[ True  True False False  True  True]
 [ True  True False  True False False]]
None


In [23]:
filter = print(arrays_a < 18)
print(filter)

[[False False  True  True False False]
 [False False  True False  True False]]
None


In [24]:
print(arrays_a[filter])

[[[44 55 12 13 44 77]
  [66 77 12 44 10 41]]]


In [15]:
filter = print(arrays_a <= 10)
print(filter)

[[False False False False False False]
 [False False False False  True False]]
None


In [25]:
print(arrays_a[filter])

[[[44 55 12 13 44 77]
  [66 77 12 44 10 41]]]


In [21]:
filter = print(np.any(10 <= 88))


True


In [20]:
print(filter)

None


In [22]:
filter = print(np.all(10 <= 88 ))

True


# create numpy program  to create an array of  10 zeros,10 ones, 10 fives

In [32]:
array_10 = np.zeros((10,10))

In [33]:
print(array_10)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [34]:
array1_10 = np.ones((10,10))
print(array1_10)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [36]:
array2_10 = np.full((10,10),5.)

In [37]:
print(array2_10)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


# QUESTION 3

#numpy program to compute sum of all elements

x = np.array([[12,13,14,15,16],[20,21,22,23,24]], dtype=np.int)
y = np.array([[60.1,62.1,63.1,64.1,65.1],[63.1,64.1,65.1,66.1,67.1]], dtype=np.float64)

In [65]:
print(x)

[[12 13 14 15 16]]


In [52]:
print(x)
#print(y)

[[12 13 14 15 16]
 [20 21 22 23 24]]


In [53]:
print(y)

[[60.1 62.1 63.1 64.1 65.1]
 [63.1 64.1 65.1 66.1 67.1]]


In [54]:
print(np.add(x,y))

[[72.1 75.1 77.1 79.1 81.1]
 [83.1 85.1 87.1 89.1 91.1]]


# Question 4

In [56]:
#numpy program to add , multiply, subtract, divide argument element wise

In [57]:
x = np.array([[12,13,14,15,16]], dtype=np.int)
y = np.array([[60.1,62.1,63.1,64.1,65.1]], dtype=np.float64)

In [58]:
print(x)

[[12 13 14 15 16]]


In [59]:
print(y)

[[60.1 62.1 63.1 64.1 65.1]]


In [61]:
#add
print(np.add(x,y))

[[72.1 75.1 77.1 79.1 81.1]]


In [62]:
# subtract
print(np.subtract(x,y))

[[-48.1 -49.1 -49.1 -49.1 -49.1]]


In [63]:
#multiply
print(np.multiply(x,y))

[[ 721.2  807.3  883.4  961.5 1041.6]]


In [64]:
#divide
print(np.divide(x,y))

[[0.19966722 0.20933977 0.22187005 0.23400936 0.24577573]]


# Question 5

In [66]:
import numpy as np
print("sine:array of angles given in degrees")

sine:array of angles given in degrees


# sin

In [69]:
print(np.sin(np.array((0.,30.,45.,60.,90.)) * np.pi/180.))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [70]:
print(np.sin(45))

0.8509035245341184


# cos

In [71]:
print(np.cos(np.array((0.,30.,45.,60.,90.)) * np.pi/180.))

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [72]:
print(np.cos(45))

0.5253219888177297


# tangent

In [78]:
print(np.tan(45))

1.6197751905438615


In [81]:
print("tangent: array of angles given in degrees")


tangent: array of angles given in degrees


In [82]:
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [83]:
print(np.tan(90))

-1.995200412208242


# pandas program
# Question6

In [93]:
import pandas as pd

d = {'one' : pd.Series([33.,43.,53.], index=['car','house','phone']),
'two': pd.Series([90.,120.,140.,320.],index=['boys','girls','jojo','superman'])    
    }

In [94]:
df = pd.DataFrame(d)
print(df)

           one    two
boys       NaN   90.0
car       33.0    NaN
girls      NaN  120.0
house     43.0    NaN
jojo       NaN  140.0
phone     53.0    NaN
superman   NaN  320.0


In [95]:
d

{'one': car      33.0
 house    43.0
 phone    53.0
 dtype: float64,
 'two': boys         90.0
 girls       120.0
 jojo        140.0
 superman    320.0
 dtype: float64}

In [96]:
df.index

Index(['boys', 'car', 'girls', 'house', 'jojo', 'phone', 'superman'], dtype='object')

In [132]:
data = [{'name':3,'score':2},{'ppl': 5,'tanti': 10, 'alice':20}]

In [133]:
df = pd.DataFrame(data)

In [135]:
print(df)

   name  score  ppl  tanti  alice
0   3.0    2.0  NaN    NaN    NaN
1   NaN    NaN  5.0   10.0   20.0


In [136]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [137]:
data[0]

{'name': 3, 'score': 2}

# Question 7

In [138]:
pd.DataFrame(data)

name  score  ppl  tanti  alice
0   3.0    2.0  NaN    NaN    NaN
1   NaN    NaN  5.0   10.0   20.0

In [139]:
dt = pd.DataFrame(d,index=['20','45','70','80','100'], columns=['name','score','black','green','white'])

In [121]:
print(dt)

    name score black green white
20   NaN   NaN   NaN   NaN   NaN
45   NaN   NaN   NaN   NaN   NaN
70   NaN   NaN   NaN   NaN   NaN
80   NaN   NaN   NaN   NaN   NaN
100  NaN   NaN   NaN   NaN   NaN


In [140]:
dt.columns[0]

'name'

In [141]:
dt.columns[1]

'score'

In [124]:
dt.columns[0:2]

Index(['name', 'score'], dtype='object')

# Question 8

In [142]:
# join 2 Dataframe

In [143]:
df

name  score  ppl  tanti  alice
0   3.0    2.0  NaN    NaN    NaN
1   NaN    NaN  5.0   10.0   20.0

In [144]:
dt

name score black green white
20   NaN   NaN   NaN   NaN   NaN
45   NaN   NaN   NaN   NaN   NaN
70   NaN   NaN   NaN   NaN   NaN
80   NaN   NaN   NaN   NaN   NaN
100  NaN   NaN   NaN   NaN   NaN

In [145]:
df_outer = pd.merge(df, dt,df_outer  on='name', how='outer')

df_outer)

SyntaxError: invalid syntax (<ipython-input-145-32727e2508ee>, line 1)