# Question1

In [1]:
#Use Use Data set and show the accuracy though the SVM model

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [17]:
import os
os.chdir('/home/billo/AI-ML')


In [42]:
data_set = pd.read_csv('userdataset1.csv')

In [43]:
data_set.head(1)

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0

In [50]:
X = data_set.iloc[:,[2,3]].values
y = data_set.iloc[:, 4].values

In [51]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.26)

In [52]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.20)

In [53]:
# Polynomial Kernel
from sklearn import metrics
from sklearn.svm import SVC
svcclassifier = SVC(kernel='poly', degree=8)
svcclassifier.fit(x_train,y_train)


SVC(degree=8, kernel='poly')

In [54]:
#making Predictions
y_pred = svcclassifier.predict(x_test)

In [55]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [56]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[46  3]
 [21 10]]
              precision    recall  f1-score   support

           0       0.69      0.94      0.79        49
           1       0.77      0.32      0.45        31

    accuracy                           0.70        80
   macro avg       0.73      0.63      0.62        80
weighted avg       0.72      0.70      0.66        80



In [57]:
# Gaussian kernel
from sklearn.svm import SVC
svclassifier = SVC(kernel= 'rbf')
svclassifier.fit(x_train,y_train)

SVC()

In [59]:
y_pred = svclassifier.predict(x_test)

In [61]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[46  3]
 [15 16]]
              precision    recall  f1-score   support

           0       0.75      0.94      0.84        49
           1       0.84      0.52      0.64        31

    accuracy                           0.78        80
   macro avg       0.80      0.73      0.74        80
weighted avg       0.79      0.78      0.76        80

